name: Code Standards
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          coverage: none
      - run: composer install --prefer-dist --no-progress
      - run: composer run lint
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          coverage: none
      - run: composer install --prefer-dist --no-progress
      - run: composer run phpstan
