name: Plugin Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  plugin-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: '8.2'
          coverage: none
      - name: Build a clean package
        run: |
          bash build.sh
          mkdir -p build
          unzip -q ../dist/video-flow-audit-for-tutor-lms-*.zip -d build
      - name: Run WordPress Plugin Check
        uses: wordpress/plugin-check-action@10857da14b6c2246d15402b3e69f777edcf8c12e # v1
        with:
          build-dir: build/video-flow-audit-for-tutor-lms
